#!/usr/bin/env node
// Bakes build info into src/shared/version.ts so the running app can report what it is.
// Runs before every build; the committed file holds safe defaults so a fresh clone type-checks.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "src/shared/version.ts");

const version = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8")).version ?? "0.0.0";

function commit() {
  // Cloudflare Workers Builds / Pages expose the SHA; a plain clone has git; a tarball has neither.
  const fromEnv = process.env.WORKERS_CI_COMMIT_SHA || process.env.CF_PAGES_COMMIT_SHA || process.env.GITHUB_SHA;
  if (fromEnv) return fromEnv.slice(0, 7);
  try {
    return execSync("git rev-parse --short HEAD", { cwd: root, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return "unknown";
  }
}

const body = `// Generated by scripts/gen-version.mjs — do not edit by hand.
export const VERSION = ${JSON.stringify(version)};
export const COMMIT = ${JSON.stringify(commit())};
export const BUILT_AT = ${JSON.stringify(new Date().toISOString())};
`;

writeFileSync(out, body);
console.log(`version: ${version} (${commit()})`);
